name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (CMake, Make, GCC, etc.)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build and run tests
      run: |
        cd laboratorio8
        mkdir -p build
        cd build
        cmake ..
        make
        ./test_calculator
        ./test_authentication
        ./test_seed

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production
      run: echo "Deploying to production server"
      # Aquí se podría agregar un script real de despliegue
